name: Update Top Langs

on:
  schedule:
    - cron: "0 0 * * *" # todo dia à meia-noite
  workflow_dispatch: # permite rodar manualmente

jobs:
  update_top_langs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests pandas matplotlib

      - name: Run Top Langs script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          python scripts/top_langs.py

      - name: Commit and push updated graph
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add top_langs.png
          git commit -m "Update Top Langs graph" || echo "No changes to commit"
          git push
